FROM python:3.9-slim

WORKDIR /usr/src/app

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements.txt .

RUN pip install --no-cache-dir -v -r requirements.txt

CMD ["/bin/bash"]
