name: delete old Releases

on:
  workflow_dispatch:

jobs:
  deleteReleases:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./.github/workflows
    steps:
      - uses: actions/checkout@master
      - name: Delete Releases
        uses: sgpublic/delete-release-action@v1.2
        with:
          # repo: '<owner>/<repoName>' # you can input a another repo here, defaults to current repo
          release-drop: true
          release-keep-count: 30
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}