name: recompress files in data

on:
  workflow_dispatch:
jobs:
  recompressData:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./.github/workflows
    steps:
      - uses: actions/checkout@master
      - name: recompress
        id: recompress
        run: ./recompress.sh
        continue-on-error: true
        working-directory: ./
        timeout-minutes: 90
      - name: Commit files
        if: steps.recompress.outcome == 'success'
        working-directory: ./
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ${{ steps.recompress.outputs.pushlist }}
          git status -s
          git commit -m "recompress files on $(date '+%Y-%m-%dT%H:%M:%SZ')"
      - name: Push changes
        if: steps.recompress.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true